### ISSUE TITLE
[Request] README: Please define 'JWE' and 'JWK'

### ISSUE THREAD

**Issue by elimisteve** [telehash/v4#1]
Thanks!

**Comment by dwaite** [comment]
JOSE, the JavaScript Object Signing and Encryption working group of the IETF, defined JSON Web Signatures and JSON Web Encryption. I'll look at a pull request with more hyperlink descriptions in the README.

**Comment by elimisteve** [comment]
Thanks :-).

**Comment by dwaite** [comment]
See Pull Request (#2)
